package snapsort;

public enum TimeStampSource {
  EXIF_DATE_TIME,
  EXIF_DATE_TIME_ORIGINAL,
  EXIF_DATE_TIME_DIGITIZED,
  EXIF_GPS_DATE_TIME,
  CAMERA_FILE_NAME,
  FINAL_FILE_NAME,
  FILE_LAST_MODIFIED,
  COLLISION_AVOIDANCE
}
